### ISSUE TITLE
Can't run - errors relating to `ajv-keywords` package

### ISSUE THREAD

**Issue by RichardWarfield** [KiwiTalk/KiwiTalk#1039]
When I try to run `npm install` `npm run start` I get lots of errors like the below for various .svg files.  Looks like this is possibly due to a version mismatch with the `ajv-keywords` package somewhere, as hinted in this [issue](https://github.com/facebook/docusaurus/issues/6073).

```
ERROR in ./src/assets/images/icon_new_chat.svg
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: Unknown keyword formatMinimum
    at get (/home/richard/workspace/third_party/KiwiTalk/node_modules/schema-utils/node_modules/ajv-keywords/dist/index.js:25:15)
    at ajvKeywords (/home/richard/workspace/third_party/KiwiTalk/node_modules/schema-utils/node_modules/ajv-keywords/dist/index.js:10:13)
    at Object.<anonymous> (/home/richard/workspace/third_party/KiwiTalk/node_modules/schema-utils/dist/validate.js:65:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/richard/workspace/third_party/KiwiTalk/node_modules/schema-utils/dist/index.js:6:5)
```

**Comment by gabrielpanegrossi** [comment]
Still same problem from https://github.com/facebook/docusaurus/issues/6073
